const list = [
  {
    id: 1,
    title: "Atomic Habits",
    author: "James Clear",
    price: 45,
    img: "https://cdnwpseller.gramedia.com/wp-content/uploads/2021/11/25135505/atomic-habits-1-561x838.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "Laut Bercerita",
    author: "Leila S. Chudori",
    price: 30,
    img: "https://cdn.gramedia.com/uploads/items/9786024246945_Laut-Bercerita.png",
    amount: 1,
  },
  {
    id: 3,
    title: "Secrets of Divine Love",
    author: "A. Helwa",
    price: 35,
    img: "https://cdn.gramedia.com/uploads/items/Secrets_of_Divine_Love_A_Spiritual_Journey_into_the_Heart_of_Islam.png",
    amount: 1,
  },
  {
    id: 4,
    title: "Kita Pergi Hari Ini",
    author: "Ziggy Zezsyazeoviennazabrizkie",
    price: 20,
    img: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1634170562i/59345269.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "The Midnight Library",
    author: "Matt Haig",
    price: 40,
    img: "https://i0.wp.com/ebooks.gramedia.com/ebook-covers/65176/image_highres/dzejjrgfydmh4mwovkha9p8j9sm7gd.jpg?w=600&ssl=1",
    amount: 1,
  },
  {
    id: 6,
    title: "Saphiens Grafis Vol. 2",
    author: "Yuval Noah Harari, David Vandermeulen, Daniel Casanave",
    price: 35,
    img: "https://i0.wp.com/ebooks.gramedia.com/ebook-covers/69688/image_highres/BLK_SGVPP2022220207.jpg?w=600&ssl=1",
    amount: 1,
  },
  {
    id: 7,
    title: " Black Showman dan Pembunuhan di Kota Tak Bernama",
    author: "Keigo Higashino",
    price: 30,
    img: "https://cdn.gramedia.com/uploads/items/Black_Showman_cov.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Cantik Itu Luka",
    author: "Eka Kurniawan",
    price: 40,
    img: "https://s3-ap-southeast-1.amazonaws.com/ebook-previews/41260/148465/1.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Filosofi Teras",
    author: "Henry Manampiring",
    price: 45,
    img: "https://cdn.gramedia.com/uploads/items/45496/thumb_image_normal/ID_FITE2018MTH12.jpg",
    amount: 1,
  },
];

export default list;